apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-agent
  namespace: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-agent
  template:
    metadata:
      labels:
        app: default-agent
    spec:
      containers:
        - name: default-agent
          image: bara/default-agent:latest
          ports:
            - containerPort: 8090
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: GOOGLE_API_KEY
            - name: APP_VERSION
              value: 'local'
            - name: SERVICE_NAME
              value: 'bara-default-agent'
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8090
            initialDelaySeconds: 15
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: default-agent
  namespace: core
spec:
  selector:
    app: default-agent
  ports:
    - port: 8090
      targetPort: 8090
