spring:
  application:
    name: bara-auth
  data:
    mongodb:
      uri: mongodb://localhost:27017/bara-auth

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
