apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - data/mongodb.yaml
  - data/redis.yaml
  - data/kafka.yaml
  - core/auth.yaml
  - core/fe.yaml
  - gateway/traefik-config.yaml
  - gateway/routes.yaml
